import NavBar from '@/components/NavBar';
import localFont from 'next/font/local';

import '@/app/globals.css';

import { Inter } from 'next/font/google';
import Header from '@/components/Header';

import { Providers } from './providers';
import Footer from '@/partials/footer';

const inter = Inter({ subsets: ['latin'] });

const myFont = localFont({
  src: '../../public/fonts/Satoshi-Variable.woff2',
});

export const metadata = {
  title: 'Pro Investors',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Providers>
          <div className={`bg-base-100 text-[#F2F2F2] `}>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
